WITH DAT AS (
SELECT
	C.CATEGORY_NAME,
	D.PRODUCT_ID,
	D.UNIT_PRICE,
	D.DISCOUNT,
	D.ORDER_ID,
	D.quantity,
	CASE
		WHEN D.UNIT_PRICE * (1 - D.DISCOUNT) < 20 THEN '1. BELOW $20'
		WHEN D.UNIT_PRICE * (1 - D.DISCOUNT) BETWEEN 20 AND 50 THEN '2. $20 - $50'
		ELSE '3. OVER $50'
	END AS PRICE_RANGE
FROM
	ORDER_DETAILS D
INNER JOIN
        PRODUCTS P ON
	D.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN
        CATEGORIES C ON
	P.CATEGORY_ID = C.CATEGORY_ID
)
SELECT
	CATEGORY_NAME,
	PRICE_RANGE,
	CAST(SUM(UNIT_PRICE * (1 - DISCOUNT)* quantity) AS INT) AS TOTAL_AMOUNT,
	COUNT(DISTINCT ORDER_ID) AS ORDER_VOLUME
FROM
	DAT
GROUP BY
	CATEGORY_NAME,
	PRICE_RANGE
ORDER BY
	CATEGORY_NAME ASC,
	PRICE_RANGE ASC;
